  
version: '3.7'

services:
  iris:
    build:
      dockerfile: Dockerfile
      context: .
    image: iscreports-iris:latest
    container_name: iris
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - ./shared:/shared

  jrserver:
    depends_on:
      - iris
    build:
      dockerfile: Dockerfile
      context: JRServer
    image: iscreports-jrserver:latest
    container_name: jrserver
    ports:
      - "8888:8888"
      - "59995:59995"
      - "59999:59999"      
    volumes:
      - ./shared:/shared
